# Generated by Django 6.0.6 on 2026-07-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Crear ticket', 'Crear ticket'), ('Actualizar ticket', 'Actualizar ticket'), ('Cerrar ticket', 'Cerrar ticket')], max_length=50)),
                ('tiempo_operacion_ms', models.IntegerField()),
                ('estado_resultante', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
